name: "GlitchPatcher"
version: "0.3.4 BETA"
main: me.exel80.glitchpatcher.gp
commands:
   gp:
      description: GlitchPatcher command.
   gp reload:
      description: Reload GlitchPatcher config.
permissions:
  glitchpatcher.*:
     description: All permissions.
     default: op
     children:
       glitchpatcher.reload: true
       glitchpatcher.update: true
  glitchpatcher.reload:
      description: Permission to use /gp reload
      default: op
  glitchpatcher.update:
      description: Permission to use /gp update
      default: op